=== Bangojetty/lifeburn/Data/CardSchema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "Card",
	"type": "object",
	"properties": {
		"id": {
			"type": "integer"
		},
		"name": {
			"type": "string"
		},
		"cost": {
			"type": "integer"
		},
		"type": {
			"$ref": "DefinitionSchema.json#/cardType"
		},
		"attack": {
			"type": "integer"
		},
		"defense": {
			"type": "integer"
		},
		"keywords": {
			"type": "array",
			"items": {
				"$ref": "DefinitionSchema.json#/keyword"
			}
		},
		"tribe": {
			"$ref": "DefinitionSchema.json#/tribe"
		},
		"rarity": {
			"type": "string",
			"enum": [ "common", "uncommon", "rare" ]
		},
		"description": {
			"type": "string"
		},
		"stackEffects": {
			"type": "array",
			"items": {
				"$ref": "EffectSchema.json"
			}
		},
		"triggeredEffects": {
			"type": "array",
			"items": {
				"$ref": "TriggerSchema.json"
			}
		},
		"passiveEffects": {
			"type": "array",
			"items": {
				"$ref": "PassiveSchema.json"
			}
		},
		"activatedEffects": {
			"type": "array",
			"items": {
				"$ref": "ActiveSchema.json"
			}
		},
		"costModifiers": {
			"type": "array",
			"items": {
				"$ref": "CostModifierSchema.json"
			}
		},
		"additionalCosts": {
			"type": "array",
			"items": {
				"$ref": "AdditionalCostSchema.json"
			}
		},
		"alternateCosts": {
			"type": "array",
			"items": {
				"$ref": "AlternateCostSchema.json"
			}
		},
		"castRestrictions": {
			"type": "array",
			"items": {
				"type": "string",
				"enum": ["onOpponentAttack", "inResponse", "opponentsTurn", "controlGoblin"]
			}
		}
	}
}

=== Bangojetty/lifeburn/Data/Cards/019_MoltenGravel.json
{
  "id": 19,
  "name": "Molten Gravel",
  "cost": 1,
  "type": "summon",
  "attack": 0,
  "defense": 0,
  "keywords": ["blitz"],
  "tribe": "golem",
  "rarity": "common",
  "description": "Molten Gravel gets +1/+1 for each stone you control. If you have 10 or more stones, Molten Gravel has trample.",
  "passiveEffects": [
    {
      "passive": "changeStats",
	  "statModifiers": [
		{
		  "statType": "attack",
		  "operatorType": "add",
		  "amountBasedOn": "stonesControlled"
		},
		{
		  "statType": "defense",
		  "operatorType": "add",
		  "amountBasedOn": "stonesControlled"
		}
	  ],
	  "scope": "selfOnly"
    },
    {
      "conditions": [
        {
          "condition": "control",
          "tokenType": "stone",
          "minAmount": 10
        }
      ],
      "passive": "grantKeyword",
      "keyword": "trample",
	  "scope": "selfOnly"
    }
  ]
}

=== Bangojetty/lifeburn/Data/Cards/255_Rewind.json
{
  "id": 255,
  "name": "Rewind",
  "cost": 0,
  "type": "spell",
  "tribe": "merfolk",
  "rarity": "uncommon",
  "description": "Rewind can only be played in response to another spell, and only during your opponents turn. Counter all spells on the stack. Your opponent restarts their turn.",
  "castRestrictions": ["inResponse", "opponentsTurn"], 
  "stackEffects": [
    {
      "effect": "counter",
      "all": true 
    },
    {
      "effect": "goToPhase",
      "phase": "draw",
      "isOpponent": true
    }
  ] 
}

=== Bangojetty/lifeburn/Data/Cards/235_Spectralize.json
{
  "id": 235,
  "name": "Spectralize",
  "cost": 4,
  "type": "spell",
  "tribe": "shadow",
  "rarity": "common",
  "description": "Exile target summon and return it to play. Give it Spectral. If it's a ghost, gain 2 LPs",
  "stackEffects": [
    {
      "effect": "exileAndReturn",
      "targetType": "summon",
      "additionalEffects": [
        {
          "effect": "grantKeyword",
          "keyword": "spectral" 
        },
        {
          "conditions": [
            {
              "condition": "rootTargetTribe",
              "tribe": "shadow"
            }
          ],
          "effect": "gainLife",
          "amount": 2
        }
      ]
    }
  ]
}

=== Bangojetty/lifeburn/Data/Cards/083_CounterBalance.json
{
  "id": 83,
  "name": "Counter Balance",
  "cost": 3,
  "type": "spell",
  "tribe": "merfolk",
  "rarity": "common",
  "description": "Counter target spell. If that spell was a non-summon, its controller gains LPs equal to its cost or draws a card.",
  "stackEffects": [
  {
    "effect": "counter",
    "additionalEffects": [
      {
        "condition": "targetNotSummon",
        "effects": [
          {
            "effect": "choose",
            "playerBasedOn": "ownerOfTarget",
		    "choiceIndex": 0,
            "choices": [
              {
                "effect": "gainLife",
                "playerBasedOn": "ownerOfTarget", 
                "amountBasedOn": "targetCost"
              },
              {
                "effect": "draw",
                "playerBasedOn": "ownerOfTarget",
                "amount": 1  
              }
            ] 
          }
        ] 
      }
    ] 
  }
  ] 
}

=== Bangojetty/lifeburn/Data/Cards/143_SpearGob.json
{
  "id": 143,
  "name": "Spear Gob",
  "cost": 0,
  "type": "summon",
  "attack": 1,
  "defense": 1,
  "keywords": ["blitz"],
  "tribe": "goblin",
  "rarity": "common",
  "description": "When spear gob enters play, deal 1 damage to any target.",
  "triggeredEffects": [
    {
      "trigger": "enteredZone",
      "zone": "play",
      "effects": [
        {
          "effect": "dealDamage",
          "targetType": "any",
          "amount": 1 
        }
      ]
    }
  ]
}

=== Bangojetty/lifeburn/Data/Cards/197_NaturalStatePlant.json
{
  "id": 197,
  "name": "Natural state Plant",
  "cost": 0,
  "type": "summon",
  "attack": 1,
  "defense": 1,
  "tribe": "treefolk",
  "rarity": "common",
  "description": "Sacrifice from play or Exile Natural state Plant from graveyard, and choose one: \n {c0}-Exile 2 cards from a graveyard. \n {c0}-Return another Treefolk from your graveyard to hand.",
  "activatedEffects": [
    {
      "costType": "sacrifice",
      "effects": [
        {
          "effect": "choose",
		  "choiceIndex": 0,
          "choices": [
            [
              {
                "effect": "sendToZone",
                "targetZone": "graveyard",
                "destination": "exile",
                "amount": 2
              }
            ],
            [
              {
                "effect": "sendToZone",
                "targetZone": "graveyard",
                "destination": "hand",
                "amount": 1
              }
            ]
          ] 
        }
      ] 
    },
    {
      "conditions": [
        {
          "condition": "inZone",
          "zone": "graveyard"
        }
      ],
      "costType": "exile",
      "effects": [
        {
          "effect": "choose",
		  "choiceIndex": 0,
          "choices": [
            [
              {
                "effect": "sendToZone",
                "targetZone": "graveyard",
                "destination": "exile",
                "amount": 2
              }
            ],
            [
              {
                "effect": "sendToZone",
                "targetZone": "graveyard",
                "destination": "hand",
                "amount": 1
              }
            ]
          ] 
        }
      ] 
    }
  ]
}

=== Bangojetty/lifeburn/Data/Cards/228_DeeprootGuard.json
{
  "id": 228,
  "name": "Deeproot Guard",
  "cost": 0,
  "type": "summon",
  "attack": 0,
  "defense": 5,
  "tribe": "treefolk",
  "rarity": "common",
  "description": "when Deeproot Guard enters play, opponent may have you sacrifice Deeproot Guard. If they do, create 2 herbs.",
  "triggeredEffects": [
    {
      "trigger": "enteredZone",
      "zone": "play",
      "optional": true,
      "opponentsChoice": true,
	  "optionMessage": "Have opponent sacfrifice Deeproot Guard and have them create 2 herbs?",
      "effects": [
        {
          "effect": "sacrifice"
        },
		{
		  "effect": "createToken",
		  "tokenType": "herb",
		  "amount": 2
		}
	  ]
	}
  ] 
}

=== Bangojetty/lifeburn/Data/Cards/224_Green-Sun.json
{
  "id": 224,
  "name": "Green-Sun",
  "cost": 9,
  "type": "spell",
  "tribe": "treefolk",
  "rarity": "uncommon",
  "description": "As an additional cost to cast Green-Sun, sacrifice a treefolk summon. Tutor a treefolk into play.",
  "additionalCosts": [
    {
      "costType": "sacrifice",
      "cardType": "summon",
      "tribe": "treefolk"
    }
  ],
  "stackEffects": [
    {
      "effect": "tutor",
      "cardType": "summon",
      "tribe": "treefolk",
      "destination": "play"
    }
  ]
}
