=== Bangojetty/lifeburn/Data/CardSchema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "Card",
	"type": "object",
	"properties": {
		"id": {
			"type": "integer"
		},
		"name": {
			"type": "string"
		},
		"cost": {
			"type": "integer"
		},
		"type": {
			"$ref": "DefinitionSchema.json#/cardType"
		},
		"attack": {
			"type": "integer"
		},
		"defense": {
			"type": "integer"
		},
		"keywords": {
			"type": "array",
			"items": {
				"$ref": "DefinitionSchema.json#/keyword"
			}
		},
		"tribe": {
			"$ref": "DefinitionSchema.json#/tribe"
		},
		"rarity": {
			"type": "string",
			"enum": [ "common", "uncommon", "rare" ]
		},
		"description": {
			"type": "string"
		},
		"stackEffects": {
			"type": "array",
			"items": {
				"$ref": "EffectSchema.json"
			}
		},
		"triggeredEffects": {
			"type": "array",
			"items": {
				"$ref": "TriggerSchema.json"
			}
		},
		"passiveEffects": {
			"type": "array",
			"items": {
				"$ref": "PassiveSchema.json"
			}
		},
		"activatedEffects": {
			"type": "array",
			"items": {
				"$ref": "ActiveSchema.json"
			}
		},
		"costModifiers": {
			"type": "array",
			"items": {
				"$ref": "CostModifierSchema.json"
			}
		},
		"additionalCosts": {
			"type": "array",
			"items": {
				"$ref": "AdditionalCostSchema.json"
			}
		},
		"alternateCosts": {
			"type": "array",
			"items": {
				"$ref": "AlternateCostSchema.json"
			}
		},
		"castRestrictions": {
			"type": "array",
			"items": {
				"type": "string",
				"enum": ["onOpponentAttack", "inResponse", "opponentsTurn", "controlGoblin"]
			}
		}
	}
}

=== Bangojetty/lifeburn/Data/Cards/173_Smite.json
{
  "id": 173,
  "name": "Smite",
  "cost": 3,
  "type": "spell",
  "tribe": "goblin",
  "rarity": "common",
  "description": "Deal 3 damage to any target. If you control a Goblin, deal 4 instead.",
  "stackEffects": [
    {
      "effect": "dealDamage",
      "targetType": "any",
      "amount": 3,
      "amountModifier": "+1",
      "modifierConditions": [
        {
          "condition": "control",
          "tribe": "goblin",
          "minAmount": 1
        }
      ]
    }
  ]
}

=== Bangojetty/lifeburn/Data/Cards/096_DuskWraith.json
{
  "id": 96,
  "name": "Dusk Wraith",
  "cost": 0,
  "type": "summon",
  "attack": 1,
  "defense": 1,
  "tribe": "shadow",
  "rarity": "common",
  "description": "When Dusk Wraith is milled, destroy target summon. If you can't, gain 3 LPs.",
  "triggeredEffects": [
    {
      "trigger": "mill",
      "scope": "selfOnly",
      "description": "Destroy target summon. If you can't, gain 3 LPs.",
      "effects": [
        {
          "effect": "destroy",
          "targetType": "summon",
          "conditions": [{ "condition": "summonsInPlay" }]
        },
        {
          "effect": "gainLife",
          "amount": 3,
          "conditions": [{ "condition": "noSummonsInPlay" }]
        }
      ]
    }
  ]
}

=== Bangojetty/lifeburn/Data/Cards/025_BrassGolem.json
{
  "id": 25,
  "name": "Brass Golem",
  "cost": 2,
  "type": "summon",
  "attack": 1,
  "defense": 1,
  "tribe": "golem",
  "rarity": "common",
  "description": "When Brass Golem enters play, create a golem with attack and defense equal to the number of stones you control.",
  "triggeredEffects": [
    {
      "trigger": "enteredZone",
      "zone": "play",
      "effects": [
        {
          "effect": "createToken",
          "tokenType": "golem",
          "attackBasedOn": "stonesControlled",
          "defenseBasedOn": "stonesControlled",
		  "description": "create a golem with attack and defense equal to the number of stones you control."
       }
      ]
    }
  ]
}

=== Bangojetty/lifeburn/Data/Cards/029_Quarry.json
{
  "id": 29,
  "name": "Quarry",
  "cost": 3,
  "type": "object",
  "tribe": "golem",
  "rarity": "common",
  "description": "At the beginning of your draw phase, create a stone. \n Sacrifice any number of stones: Draw that many cards, then sacrifice Quarry.",
  "triggeredEffects": [
	{
	  "trigger": "phase",
	  "phase": "draw",
	  "effect": "createToken",
	  "tokenType": "stone",
	  "amount": 1
	}
  ],
  "activatedEffects": [
  {
    "costType": "sacrifice",
	"tokenType": "stone",
    "playerChosenAmount": true,
    "effects": [
      {
        "effect": "draw",
        "amountBasedOn": "activatedCost"
      },
      {
        "effect": "sacrifice",
		"self": true
      }
    ]
  }
  ]
}

=== Bangojetty/lifeburn/Data/Cards/146_TransparentGoblin.json
{
  "id": 146,
  "name": "Transparent Goblin",
  "cost": 0,
  "type": "summon",
  "attack": 1,
  "defense": 1,
  "tribe": "goblin",
  "rarity": "common",
  "description": "Transparent Goblin does not count as your summon for turn.",
  "passiveEffects": [
    {  
      "passive": "bypassSummonLimit"
    }
  ] 
}

=== Bangojetty/lifeburn/Data/Cards/234_RitualOfDarkness.json
{
  "id": 234,
  "name": "Ritual Of Darkness",
  "cost": 11,
  "type": "spell",
  "tribe": "shadow",
  "rarity": "rare",
  "description": "Starting with you, each player may put a summon into play. Repeat until no player puts a summon into play.",
  "stackEffects": [
    {
      "effect": "cardRitualOfDarkness"
    }
  ]
}

=== Bangojetty/lifeburn/Data/Cards/269_GoblinLieutenant.json
{
  "id": 269,
  "name": "Goblin Lieutenant",
  "cost": 0,
  "type": "summon",
  "attack": 1,
  "defense": 1,
  "keywords": ["blitz"],
  "tribe": "goblin",
  "rarity": "common",
  "description": "When Goblin Lieutenant attacks, create an attacking 3/1 goblin until end of turn.",
  "triggeredEffects": [  
    {
      "trigger": "attack",
      "scope": "selfOnly",
      "effects": [
        {
          "effect": "createToken",
          "tokenType": "goblin",
          "attack": 3,
          "defense": 1,
          "amount": 1,
          "attacking": true,
          "tokenPassive": {
				"passive": "thisTurn"
		    }
        }
      ] 
    }
  ]
}

=== Bangojetty/lifeburn/Data/Cards/064_MerfolkShifter.json
{
  "id": 64,
  "name": "Merfolk Shifter",
  "cost": 1,
  "type": "summon",
  "attack": 3,
  "defense": 2,
  "keywords": ["dive"],
  "tribe": "merfolk",
  "rarity": "common",
  "description": "When Merfolk Shifter enters play, return target summon to its owner's hand.",
  "triggeredEffects": [
	  {
		"trigger": "enteredZone",
		"zone": "play",
		"effects": [
		  {
			"effect": "sendToZone",
			"targetType": "summon",
			"destination": "hand"
		  }
		]  
	  }
    ] 
}
