=== Bangojetty/lifeburn/Data/CardSchema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "Card",
	"type": "object",
	"properties": {
		"id": {
			"type": "integer"
		},
		"name": {
			"type": "string"
		},
		"cost": {
			"type": "integer"
		},
		"type": {
			"$ref": "DefinitionSchema.json#/cardType"
		},
		"attack": {
			"type": "integer"
		},
		"defense": {
			"type": "integer"
		},
		"keywords": {
			"type": "array",
			"items": {
				"$ref": "DefinitionSchema.json#/keyword"
			}
		},
		"tribe": {
			"$ref": "DefinitionSchema.json#/tribe"
		},
		"rarity": {
			"type": "string",
			"enum": [ "common", "uncommon", "rare" ]
		},
		"description": {
			"type": "string"
		},
		"stackEffects": {
			"type": "array",
			"items": {
				"$ref": "EffectSchema.json"
			}
		},
		"triggeredEffects": {
			"type": "array",
			"items": {
				"$ref": "TriggerSchema.json"
			}
		},
		"passiveEffects": {
			"type": "array",
			"items": {
				"$ref": "PassiveSchema.json"
			}
		},
		"activatedEffects": {
			"type": "array",
			"items": {
				"$ref": "ActiveSchema.json"
			}
		},
		"costModifiers": {
			"type": "array",
			"items": {
				"$ref": "CostModifierSchema.json"
			}
		},
		"additionalCosts": {
			"type": "array",
			"items": {
				"$ref": "AdditionalCostSchema.json"
			}
		},
		"alternateCosts": {
			"type": "array",
			"items": {
				"$ref": "AlternateCostSchema.json"
			}
		},
		"castRestrictions": {
			"type": "array",
			"items": {
				"type": "string",
				"enum": ["onOpponentAttack", "inResponse", "opponentsTurn", "controlGoblin"]
			}
		}
	}
}

=== Bangojetty/lifeburn/Data/Cards/211_VerdictCommand.json
{
  "id": 211,
  "name": "Verdict Command",
  "cost": 2,
  "type": "spell",
  "tribe": "treefolk",
  "rarity": "common",
  "description": "Choose two: \n {c0}-Gain 1 LP. \n {c0}-Destroy target token. \n {c0}-Remove all haunt counters in play. \n {c0}-Exile 2 cards from a graveyard.",
  "stackEffects": [
    {
      "effect": "choose",
      "amount": 2,
	  "choiceIndex": 0,
      "choices": [
        [
          {
            "effect": "gainLife",
            "amount": 1
          }
        ],
        [
          {
            "effect": "destroy",
            "targetType": "token"
          }
        ],
        [
          {
            "effect": "removeCounter",
            "counterType": "haunt", 
            "all": true
          }
        ],
        [
          {
            "effect": "sendToZone",
            "targetZone": "graveyard", 
            "destination": "exile",
            "amount": 2,
            "sameZone": true 
          }
        ]
      ]
    }
  ]
}

=== Bangojetty/lifeburn/Data/Cards/001_GolemBlinker.json
{
  "id": 1,
  "name": "Golem Blinker",
  "cost": 0,
  "type": "summon",
  "attack": 2,
  "defense": 1,
  "tribe": "golem",
  "rarity": "common",
  "description": "When a golem you control dies, you may cast this card from hand. When Golem Blinker enters play, create a stone.",
  "triggeredEffects": [
    {
      "trigger": "enteredZone",
      "zone": "play",
      "effects": [
        {
          "effect": "createToken",
          "tokenType": "stone",
          "amount": 1
        }
      ]
    },
    {
      "trigger": "death",
      "tribe": "golem",
	  "triggerZone": "hand",
	  "self": false,
      "optional": true,
	  "optionMessage": "Cast Golem Blinker without paying its cost?",
      "effects": [
        {
          "effect": "castCard",
		  "self": true
        }
      ]
    }
  ]
}

=== Bangojetty/lifeburn/Data/Cards/121_LingeringShades.json
{
  "id": 121,
  "name": "Lingering Shades",
  "cost": 2,
  "type": "summon",
  "attack": 1,
  "defense": 1,
  "tribe": "shadow",
  "rarity": "common",
  "description": "When Lingering Shades enters play, create five 1/1 ghost tokens.",
  "triggeredEffects": [
  {
    "effect": "enteredZone",
    "zone": "play",
    "effects": [
      {
        "effect": "createToken",
        "tokenType": "ghost",
        "attack": 1,
        "defense": 1,
        "amount": 5   
      }
    ]
  }
  ]
}

=== Bangojetty/lifeburn/Data/Cards/054_CuriousMerfolk.json
{
  "id": 54,
  "name": "Curious Merfolk",
  "cost": 0,
  "type": "summon",
  "attack": 1,
  "defense": 2,
  "keywords": ["dive"],
  "tribe": "merfolk",
  "rarity": "common",
  "description": "Whenever Curious Merfolk deals damage to a player, draw a card.",
  "triggeredEffects": [
  {
    "trigger": "dealDamageToPlayer",
    "self": true,
    "effects": [
      {
        "effect": "draw",
        "amount": 1
      }
    ]
  }
  ]
}

=== Bangojetty/lifeburn/Data/Cards/127_ShadowLord.json
{
  "id": 127,
  "name": "Shadow Lord",
  "cost": 3,
  "type": "summon",
  "attack": 5,
  "defense": 5,
  "tribe": "shadow",
  "rarity": "common",
  "description": "While Shadow Lord is in your graveyard, all ghosts get +1/+0 and Haunt.",
  "passiveEffects": [
	  {
		"conditions": [
		  {
			"condition": "inZone",
			"zone": "graveyard"
		  }
		],
		"passive": "changeStats",
		"tribe": "shadow",
		"statModfiers": [
			{
				"statType": "attack",
				"operatorType": "add",
				"amount": 1
			}
		]
	  },
	  {
		  "conditions": [
		  {
			"condition": "inZone",
			"zone": "graveyard"
		  }
		],
		  "passive": "grantKeyword",
		  "tribe": "shadow",
		  "keyword": "haunt"
	  }
    ]
}

=== Bangojetty/lifeburn/Data/Cards/181_Channel.json
{
  "id": 181,
  "name": "Channel",
  "cost": 0,
  "type": "spell",
  "tribe": "goblin",
  "rarity": "common",
  "description": "Deal X damage to target player. Channel cannot reduce players below 1 LP",
  "costModifiers": [
    {
      "modifier": "x", 
      "additionalModifier": "+10"
    }
  ],
  "stackEffects": [
    {
      "effect": "dealDamage",
      "targetType": "player",
      "amountBasedOn": "x",
      "restrictions": [
	  "cantReduceBelowOne" 
	  ]
    }
  ]
}

=== Bangojetty/lifeburn/Data/Cards/232_Barrage.json
{
  "id": 232,
  "name": "Barrage",
  "cost": 3,
  "type": "spell",
  "tribe": "goblin",
  "rarity": "common",
  "description": "Create a 1/1 goblin token. Deal damage equal to the number of goblins you control to any target.",
  "stackEffects": [
    {
      "effect": "createToken",
      "tokenType": "goblin",
      "attack": 1,
      "defense": 1,
      "amount": 1
    },
    {
      "effect": "dealDamage",
      "targetType": "any",
      "amountBasedOn": "goblinsControlled"
    }
  ]
}

=== Bangojetty/lifeburn/Data/Cards/214_LostSanctuary.json
{
  "id": 214,
  "name": "Lost Sanctuary",
  "cost": 3,
  "type": "spell",
  "tribe": "treefolk",
  "rarity": "common",
  "description": "Choose one: \n {c0}-Create a 1/1 Plant token. \n {c0}-Create and Herb token. \n Each player chooses one: \n {c1}-Draw a card. \n {c1}-Create an Herb token.",
  "stackEffects": [
    {
      "effect": "choose",
	  "choiceIndex": 0,
      "choices": [
        [
          {
            "effect": "createToken",
            "tokenType": "plant",
            "attack": 1,
            "defense": 1,
            "amount": 1
          }
        ],
        [
          {
            "effect": "createToken",
            "tokenType": "herb",
            "amount": 1 
          }
        ]
      ]
    },
    {
      "effect": "choose",
	  "choiceIndex": 1,
      "choices": [
        [
          {
            "effect": "draw",
            "amount": 1
          }
        ],
        [
          {
            "effect": "createToken",
            "tokenType": "herb",
            "amount": 1 
          }
        ]
      ]
    },
    {
      "effect": "choose",
	  "choiceIndex": 1,
      "isOpponent": true,
      "choices": [        [
          {
            "effect": "draw",
            "amount": 1  
          }
        ],
        [
          {
            "effect": "createToken",
            "tokenType": "herb",
            "amount": 1  
          }
        ]

      ]
    }
  ]
}
